### ISSUE TITLE
Can I add a Facebook login?

### ISSUE THREAD

**Issue by eggham0518** [KODDevYouTube/InstagramApp#1]
Thank you for your great tutorial.

I'm adding a Facebook login.
but The null value is returned from this point.

All I did was add this code.
implementation 'com.facebook.android:facebook-login:[4,5)'

In ProfileFragment.java

    public void userInfo(){
        DatabaseReference reference = FirebaseDatabase.getInstance().getReference("Users").child(profileid);
        reference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                if (getContext() == null){
                    return;
                }
               User user = dataSnapshot.getValue(User.class);

                Glide.with(getContext()).load(user.getImageurl()).into(image_profile);
                username.setText(user.getUsername());
                fullname.setText(user.getFullname());
                bio.setText(user.getBio());

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });
    }

      Process: com.devkang.mystar, PID: 23381
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.devkang.mystar.Model.User.getImageurl()' on a null object reference
        at com.devkang.mystar.Fragments.ProfileFragment$7.onDataChange(ProfileFragment.java:214)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.5:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.5:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.5:55)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by anfaas1618** [comment]
you need to loop the datasnapshots.getchildren
